on:
  push:
    branches: 
      - 'main'

jobs:
  run:
    runs-on: ubuntu-20.04
    name: Run File
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          java-package: jdk
      - run: java -cp java QuizSimulation
